version: '3.3'
services:
  application:
    image: remedy
    container_name: remedy
    env_file: .env.dev
    environment:
      - DATABASE_URL=postgres://postgres:development@postgresql/remedy_dev
    ports:
      - 4000:4000
    depends_on:
      - postgresql
  postgresql:
    image: postgres:10
    container_name: remedy-postgres
    environment:
      - POSTGRES_DB=remedy_dev
      - POSTGRES_PASSWORD=development
    ports:
      - 5432:5432
    volumes:
      - remedy_psql:/var/lib/postgresql/data
volumes:
  remedy_psql:
